---
title: "캐글 Advanced 머신러닝 실전 박치기 연습 in R"
output:
  html_document:
    df_print: paged
---

# 캐글 Advanced 머신러닝 실전 박치기 연습
* 원래 강좌는 python으로 진행하는데 r로도 연습하면 좋겠다 싶어서 하는 것

## 쓸 라이브러리 로딩
```{r}
library(dplyr)
library(mosaic)
library(ggplot2)
library(gridExtra) 
```

## 기본 데이터 로딩
```{r}
default_dir = './data'
app_train = read.csv(file.path(default_dir, 'application_train.csv'), header=TRUE, na.strings="NA")
app_test = read.csv(file.path(default_dir, 'application_test.csv'), header=TRUE, na.strings="NA")
```

## 데이터 시각화
### TARGET 값 분포 및 AMT_INCOME_TOTAL 값 Histogram
* TARGET 값별 분포도를 시각화
```{r}
hist(app_train$AMT_INCOME_TOTAL)
```


### AMT_INCOME_TOTAL이 100000 이하인 값에 대한 분포도 그래프


```{r}
hist(filter(app_train, AMT_INCOME_TOTAL < 1000000)$AMT_INCOME_TOTAL)
```

```{r}
displayed_data = filter(app_train, AMT_INCOME_TOTAL < 1000000)$AMT_INCOME_TOTAL
hist(displayed_data, freq=F)
lines(density(displayed_data))
```

```{r}
```

```{r}
par(mfcol = c(1, 3))
hist(displayed_data, freq=F)
plot(density(displayed_data))
hist(displayed_data, freq=F)
lines(density(displayed_data))
```


### TARGET 값에 따른 AMT_INCOME_TOTAL 값 분포도 비교
 * distplot와 violinplot 으로 시각화

```{r}
cond0 = app_train$TARGET == 0
cond1 = app_train$TARGET == 1
mnt_threshold = 500000
cond_mnt = (app_train$AMT_INCOME_TOTAL < mnt_threshold)

p1 = ggplot(filter(app_train, cond_mnt & cond0), aes(x=TARGET, y=AMT_INCOME_TOTAL, fill="0")) + geom_violin() + geom_violin(data=filter(app_train, cond_mnt & cond1), aes(x=TARGET, y=AMT_INCOME_TOTAL, fill="1"))
displayed_data = filter(app_train, cond0 & cond_mnt)
p2 = ggplot(displayed_data, aes(x=AMT_INCOME_TOTAL, y=..density..)) + geom_density(fill=NA, colour=NA, alpha=0.8) + geom_line(stat="density",size=1) + geom_histogram(binwidth=10000, colour="blue", alpha=0.2) 
grid.arrange(p1, p2, ncol=2)
```


